### ISSUE TITLE
Fix Linting Issues

### ISSUE THREAD

**Issue by BenBals** [hpi-swa-teaching/Algernon-Launcher#136]
This is a large meta-issue that has many problems. The problems should be divided up.

- [x] Uses do: instead of collect: or select: (Weight: 4) @BenBals #138 
- [x] *Dot After Return Consistency* (Weight: 3) @robertkirsten #150 
      _(Please also check what the style guide says about last-line-dots without a return statement)_
- [x] ifTrue:/ifFalse returns instead of and:/or: (Weight: 1) @phlprcks -> was already refactored a while ago
- [x] intensive Coupling (Weight: 7) @sinnaj-r @BenBals #138
- [x] Law of Demeter (Weight: 9) @sinnaj-r @BenBals  #138
- [x] Long Methods (Weight: 4) @sinnaj-r #139
- [x] Sends questionable message (Weight: 1) @kej-jay 
- [ ] Sends add:/remove: to external collection (Weight: 1) @BenBals #146 
- [x] excessive number of arguments (Weight: 1) @phlprcks -> see comment below
- [x] Methods implemented but not sent (Weight: 1) @phlprcks #160 
- [x] Inconsistent method classification (Weight: 3, easy) @phlprcks -> see comment below
- [x] Temporary Variables not read and written (Weight: 3) @robertkirsten #153 
- [x] Instance Variable not read and written (Weight: 2) @robertkirsten #153 
- [x] Refers to class name instead of "self class" (Weight: 0.1) @kej-jay 
- [x] Unnecessary assignment to a temporary variable (Weight: 1) @robertkirsten #153
- [x] Unreferenced Variable (Weight: 3) @robertkirsten  #158 
	- The weight is so high, because the linter does not tell you which one (as far as I can tell)

| Team Member | Points |
|--|--|
| @sinnaj-r | 20 |
| @robertkirsten | 14 |
| @phlprcks | 6 |
| @kej-jay | 1.1 |
| @BenBals | 21 |

The weights are my subjective, imperfect measure of how time consuming and/or difficult a refactoring is as well as how much risk for escalation of time is involved. I suggest that each pair take on roughly equal amounts of weight. I welcome changes and more linting problems to be added.

This does not invalidate the "boy scout rule" that when you see one of these problems in the code you *must fix it immediatly*. That holds especially for simple refactorings like "Uses do: instead of collect: or select:".

**Comment by sinnaj-r** [comment]
While I refactored the long lines, I stumbled over the icon provider once again, in which the icons are stored as strings. Do you think we should leave it that way, or should we store them as image assets somehow?

**Comment by BenBals** [comment]
That would be nice, but we will have to weigh cost and benefit. How long do you think this will take?

**Comment by phlprcks** [comment]
> 
> 
> While I refactored the long lines, I stumbled over the icon provider once again, in which the icons are stored as strings. Do you think we should leave it that way, or should we store them as image assets somehow?

I think this is not a priority right now. It is not an extreme pain point in my opinion given that adding new icons is not frequently done.

**Comment by sinnaj-r** [comment]
> That would be nice, but we will have to weigh cost and benefit. How long do you think this will take?

Hasn't any of you from SWA already had experience how to integrate images ? (@kej-jay Maybe ?)
I, for my part, would have to read into it first.

**Comment by phlprcks** [comment]
We also have to consider that users who want to use Algernon (and potentially Algernon will be included in the squeak image in the future) have access to the icons without any trouble (or additional steps such as downloading them). That is why this might be a bit more complicated and out of scope for now in my opinion, unless @kej-jay has a master solution of course :)

**Comment by sinnaj-r** [comment]
> We also have to consider that users who want to use Algernon (and potentially Algernon will be included in the squeak image in the future) have access to the icons without any trouble (or additional steps such as downloading them). That is why this might be a bit more complicated and out of scope for now in my opinion, unless @kej-jay has a master solution of course :)

You might be right here. I also did some pointer chasing and found out that e.g. the Menu Items are hardcoded as well. 
For example have a look in `MenuIcons class>>#fugueUserSilhouetteQuestionIconContents`. Their style is a bit nicer, but ours should be okay too.

**Comment by phlprcks** [comment]
Notes (aka this is why not many changes were needed). Some of those issues there already refactored within #80 a while ago.
- excessive number of arguments (one method left, which in my opinion needs no refactoring)
- apart from accessing and exportAsSar, not sent methods were removed
- inconsistent classification of methods. Many cases where the linter suggests bad classification are actually good. For instance a lot of accessing methods are classified as such, but the superclass on a very high object level (e.g. the kernel objects) does not classify such methods as accessing (many more similar cases exist). This is why the linter will always show a lot of mehtods.
